// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for ErrorEventStage.
const (
	ErrorEventStageFindSimilar      ErrorEventStage = "find_similar"
	ErrorEventStageMap              ErrorEventStage = "map"
	ErrorEventStageScrapeRepo       ErrorEventStage = "scrape_repo"
	ErrorEventStageScrapeSite       ErrorEventStage = "scrape_site"
	ErrorEventStageSearchCollisions ErrorEventStage = "search_collisions"
	ErrorEventStageSearchContext    ErrorEventStage = "search_context"
	ErrorEventStageSynthesize       ErrorEventStage = "synthesize"
)

// Valid indicates whether the value is a known member of the ErrorEventStage enum.
func (e ErrorEventStage) Valid() bool {
	switch e {
	case ErrorEventStageFindSimilar:
		return true
	case ErrorEventStageMap:
		return true
	case ErrorEventStageScrapeRepo:
		return true
	case ErrorEventStageScrapeSite:
		return true
	case ErrorEventStageSearchCollisions:
		return true
	case ErrorEventStageSearchContext:
		return true
	case ErrorEventStageSynthesize:
		return true
	default:
		return false
	}
}

// Defines values for SourceVia.
const (
	Exa       SourceVia = "exa"
	Firecrawl SourceVia = "firecrawl"
	Http      SourceVia = "http"
)

// Valid indicates whether the value is a known member of the SourceVia enum.
func (e SourceVia) Valid() bool {
	switch e {
	case Exa:
		return true
	case Firecrawl:
		return true
	case Http:
		return true
	default:
		return false
	}
}

// Defines values for StageEventStage.
const (
	StageEventStageFindSimilar      StageEventStage = "find_similar"
	StageEventStageMap              StageEventStage = "map"
	StageEventStageScrapeRepo       StageEventStage = "scrape_repo"
	StageEventStageScrapeSite       StageEventStage = "scrape_site"
	StageEventStageSearchCollisions StageEventStage = "search_collisions"
	StageEventStageSearchContext    StageEventStage = "search_context"
	StageEventStageSynthesize       StageEventStage = "synthesize"
)

// Valid indicates whether the value is a known member of the StageEventStage enum.
func (e StageEventStage) Valid() bool {
	switch e {
	case StageEventStageFindSimilar:
		return true
	case StageEventStageMap:
		return true
	case StageEventStageScrapeRepo:
		return true
	case StageEventStageScrapeSite:
		return true
	case StageEventStageSearchCollisions:
		return true
	case StageEventStageSearchContext:
		return true
	case StageEventStageSynthesize:
		return true
	default:
		return false
	}
}

// Defines values for StageEventStatus.
const (
	Done    StageEventStatus = "done"
	Running StageEventStatus = "running"
)

// Valid indicates whether the value is a known member of the StageEventStatus enum.
func (e StageEventStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Disambiguation Draft plus the score we compute ourselves rather than ask for.
type Disambiguation struct {
	AmbiguityScore  float32          `json:"ambiguity_score"`
	NameCollisions  *[]NameCollision `json:"name_collisions,omitempty"`
	NegativeSignals *[]string        `json:"negative_signals,omitempty"`
	Notes           *string          `json:"notes,omitempty"`
	PositiveSignals *[]string        `json:"positive_signals,omitempty"`
}

// ErrorEvent defines model for ErrorEvent.
type ErrorEvent struct {
	Detail string           `json:"detail"`
	Event  *string          `json:"event,omitempty"`
	Fatal  *bool            `json:"fatal,omitempty"`
	Stage  *ErrorEventStage `json:"stage,omitempty"`
}

// ErrorEventStage defines model for ErrorEvent.Stage.
type ErrorEventStage string

// Identity defines model for Identity.
type Identity struct {
	Aliases          *[]string          `json:"aliases,omitempty"`
	CanonicalName    string             `json:"canonical_name"`
	CliCommands      *[]string          `json:"cli_commands,omitempty"`
	DocsUrl          *string            `json:"docs_url,omitempty"`
	Homepage         *string            `json:"homepage,omitempty"`
	OfficialAccounts *map[string]string `json:"official_accounts,omitempty"`
	OrgOrOwner       *string            `json:"org_or_owner,omitempty"`
	PackageNames     *[]PackageRef      `json:"package_names,omitempty"`
	Repo             *string            `json:"repo,omitempty"`
	Slug             string             `json:"slug"`
	Tagline          *string            `json:"tagline,omitempty"`
}

// NameCollision Something else that shares this product's name. Observed, never recalled.
type NameCollision struct {
	Domain        *string `json:"domain,omitempty"`
	EvidenceUrl   string  `json:"evidence_url"`
	Name          string  `json:"name"`
	WhatItIs      string  `json:"what_it_is"`
	WhyConfusable *string `json:"why_confusable,omitempty"`
}

// PackageRef defines model for PackageRef.
type PackageRef struct {
	Name     string `json:"name"`
	Registry string `json:"registry"`
}

// ProductDossier defines model for ProductDossier.
type ProductDossier struct {
	// Disambiguation Draft plus the score we compute ourselves rather than ask for.
	Disambiguation Disambiguation `json:"disambiguation"`
	Identity       Identity       `json:"identity"`
	Provenance     Provenance     `json:"provenance"`

	// Vocabulary How real users refer to the product when they talk about it.
	Vocabulary Vocabulary `json:"vocabulary"`
	What       What       `json:"what"`
}

// Provenance defines model for Provenance.
type Provenance struct {
	DegradedSources *[]string           `json:"degraded_sources,omitempty"`
	FieldConfidence *map[string]float32 `json:"field_confidence,omitempty"`
	GeneratedAt     time.Time           `json:"generated_at"`
	RuntimeMs       int                 `json:"runtime_ms"`
	Sources         *[]Source           `json:"sources,omitempty"`
}

// ResultEvent defines model for ResultEvent.
type ResultEvent struct {
	Dossier ProductDossier `json:"dossier"`
	Event   *string        `json:"event,omitempty"`
}

// Source defines model for Source.
type Source struct {
	FetchedAt time.Time `json:"fetched_at"`
	Url       string    `json:"url"`
	Via       SourceVia `json:"via"`
}

// SourceVia defines model for Source.Via.
type SourceVia string

// StageEvent defines model for StageEvent.
type StageEvent struct {
	Detail *string          `json:"detail,omitempty"`
	Event  *string          `json:"event,omitempty"`
	Stage  StageEventStage  `json:"stage"`
	Status StageEventStatus `json:"status"`
}

// StageEventStage defines model for StageEvent.Stage.
type StageEventStage string

// StageEventStatus defines model for StageEvent.Status.
type StageEventStatus string

// Vocabulary How real users refer to the product when they talk about it.
type Vocabulary struct {
	AdjacentProducts   *[]string `json:"adjacent_products,omitempty"`
	CommonMisspellings *[]string `json:"common_misspellings,omitempty"`

	// FeatureJargon Product-specific words with no namesakes. Often a better search key than the product name itself.
	FeatureJargon *[]string `json:"feature_jargon,omitempty"`
	UserTerms     *[]string `json:"user_terms,omitempty"`
}

// What defines model for What.
type What struct {
	Category        *string   `json:"category,omitempty"`
	Description     *string   `json:"description,omitempty"`
	KeyFeatures     *[]string `json:"key_features,omitempty"`
	License         *string   `json:"license,omitempty"`
	Maturity        *string   `json:"maturity,omitempty"`
	PricingModel    *string   `json:"pricing_model,omitempty"`
	PrimaryUseCases *[]string `json:"primary_use_cases,omitempty"`
	Subcategory     *string   `json:"subcategory,omitempty"`
	TargetUsers     *[]string `json:"target_users,omitempty"`
	TechStack       *[]string `json:"tech_stack,omitempty"`
}
