// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for ErrorEventStage.
const (
	ErrorEventStageBuildReport      ErrorEventStage = "build_report"
	ErrorEventStageExtractIssues    ErrorEventStage = "extract_issues"
	ErrorEventStageFindSimilar      ErrorEventStage = "find_similar"
	ErrorEventStageMap              ErrorEventStage = "map"
	ErrorEventStageMapPosts         ErrorEventStage = "map_posts"
	ErrorEventStageScrapeHackernews ErrorEventStage = "scrape_hackernews"
	ErrorEventStageScrapeReddit     ErrorEventStage = "scrape_reddit"
	ErrorEventStageScrapeRepo       ErrorEventStage = "scrape_repo"
	ErrorEventStageScrapeSite       ErrorEventStage = "scrape_site"
	ErrorEventStageSearchCollisions ErrorEventStage = "search_collisions"
	ErrorEventStageSearchContext    ErrorEventStage = "search_context"
	ErrorEventStageSelectSources    ErrorEventStage = "select_sources"
	ErrorEventStageSynthesize       ErrorEventStage = "synthesize"
)

// Valid indicates whether the value is a known member of the ErrorEventStage enum.
func (e ErrorEventStage) Valid() bool {
	switch e {
	case ErrorEventStageBuildReport:
		return true
	case ErrorEventStageExtractIssues:
		return true
	case ErrorEventStageFindSimilar:
		return true
	case ErrorEventStageMap:
		return true
	case ErrorEventStageMapPosts:
		return true
	case ErrorEventStageScrapeHackernews:
		return true
	case ErrorEventStageScrapeReddit:
		return true
	case ErrorEventStageScrapeRepo:
		return true
	case ErrorEventStageScrapeSite:
		return true
	case ErrorEventStageSearchCollisions:
		return true
	case ErrorEventStageSearchContext:
		return true
	case ErrorEventStageSelectSources:
		return true
	case ErrorEventStageSynthesize:
		return true
	default:
		return false
	}
}

// Defines values for PostSource.
const (
	Github     PostSource = "github"
	Hackernews PostSource = "hackernews"
	Reddit     PostSource = "reddit"
	X          PostSource = "x"
)

// Valid indicates whether the value is a known member of the PostSource enum.
func (e PostSource) Valid() bool {
	switch e {
	case Github:
		return true
	case Hackernews:
		return true
	case Reddit:
		return true
	case X:
		return true
	default:
		return false
	}
}

// Defines values for SourceVia.
const (
	Exa       SourceVia = "exa"
	Firecrawl SourceVia = "firecrawl"
	Http      SourceVia = "http"
)

// Valid indicates whether the value is a known member of the SourceVia enum.
func (e SourceVia) Valid() bool {
	switch e {
	case Exa:
		return true
	case Firecrawl:
		return true
	case Http:
		return true
	default:
		return false
	}
}

// Defines values for StageEventStage.
const (
	StageEventStageBuildReport      StageEventStage = "build_report"
	StageEventStageExtractIssues    StageEventStage = "extract_issues"
	StageEventStageFindSimilar      StageEventStage = "find_similar"
	StageEventStageMap              StageEventStage = "map"
	StageEventStageMapPosts         StageEventStage = "map_posts"
	StageEventStageScrapeHackernews StageEventStage = "scrape_hackernews"
	StageEventStageScrapeReddit     StageEventStage = "scrape_reddit"
	StageEventStageScrapeRepo       StageEventStage = "scrape_repo"
	StageEventStageScrapeSite       StageEventStage = "scrape_site"
	StageEventStageSearchCollisions StageEventStage = "search_collisions"
	StageEventStageSearchContext    StageEventStage = "search_context"
	StageEventStageSelectSources    StageEventStage = "select_sources"
	StageEventStageSynthesize       StageEventStage = "synthesize"
)

// Valid indicates whether the value is a known member of the StageEventStage enum.
func (e StageEventStage) Valid() bool {
	switch e {
	case StageEventStageBuildReport:
		return true
	case StageEventStageExtractIssues:
		return true
	case StageEventStageFindSimilar:
		return true
	case StageEventStageMap:
		return true
	case StageEventStageMapPosts:
		return true
	case StageEventStageScrapeHackernews:
		return true
	case StageEventStageScrapeReddit:
		return true
	case StageEventStageScrapeRepo:
		return true
	case StageEventStageScrapeSite:
		return true
	case StageEventStageSearchCollisions:
		return true
	case StageEventStageSearchContext:
		return true
	case StageEventStageSelectSources:
		return true
	case StageEventStageSynthesize:
		return true
	default:
		return false
	}
}

// Defines values for StageEventStatus.
const (
	Done    StageEventStatus = "done"
	Failed  StageEventStatus = "failed"
	Running StageEventStatus = "running"
)

// Valid indicates whether the value is a known member of the StageEventStatus enum.
func (e StageEventStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Disambiguation Draft plus the score we compute ourselves rather than ask for.
type Disambiguation struct {
	AmbiguityScore  float32          `json:"ambiguity_score"`
	NameCollisions  *[]NameCollision `json:"name_collisions,omitempty"`
	NegativeSignals *[]string        `json:"negative_signals,omitempty"`
	Notes           *string          `json:"notes,omitempty"`
	PositiveSignals *[]string        `json:"positive_signals,omitempty"`
}

// DossierEvent T0 landed. Emitted before T1 starts so the CLI can render it during the
// minutes the scrape takes, rather than holding a finished dossier back.
type DossierEvent struct {
	Dossier ProductDossier `json:"dossier"`
	Event   *string        `json:"event,omitempty"`
}

// ErrorEvent defines model for ErrorEvent.
type ErrorEvent struct {
	Detail string           `json:"detail"`
	Event  *string          `json:"event,omitempty"`
	Fatal  *bool            `json:"fatal,omitempty"`
	Stage  *ErrorEventStage `json:"stage,omitempty"`
}

// ErrorEventStage defines model for ErrorEvent.Stage.
type ErrorEventStage string

// FieldNote Everything the run produced. Grows a field per stage as T3-T5 land.
type FieldNote struct {
	Dossier ProductDossier          `json:"dossier"`
	Harvest *Harvest                `json:"harvest,omitempty"`
	Report  *map[string]interface{} `json:"report,omitempty"`
}

// HackerNewsTargets defines model for HackerNewsTargets.
type HackerNewsTargets struct {
	SearchQueries *[]string `json:"search_queries,omitempty"`
}

// Harvest T1's result: the targets chosen, and what came back from them.
type Harvest struct {
	// Live True when posts came from a live scrape. False means the scraper was unreachable and fixtures were substituted.
	Live          bool      `json:"live"`
	MappingErrors *[]string `json:"mapping_errors,omitempty"`
	Posts         *[]Post   `json:"posts,omitempty"`
	SourceNote    string    `json:"source_note"`

	// Targets T1's output: what to scrape, derived from the dossier's discriminator.
	Targets ScrapeTargets `json:"targets"`
}

// HarvestEvent defines model for HarvestEvent.
type HarvestEvent struct {
	Event *string `json:"event,omitempty"`

	// Harvest T1's result: the targets chosen, and what came back from them.
	Harvest Harvest `json:"harvest"`
}

// HeartbeatEvent Keeps the connection and the UI alive across a multi-minute scrape.
type HeartbeatEvent struct {
	ElapsedMs int     `json:"elapsed_ms"`
	Event     *string `json:"event,omitempty"`
}

// Identity defines model for Identity.
type Identity struct {
	Aliases          *[]string          `json:"aliases,omitempty"`
	CanonicalName    string             `json:"canonical_name"`
	CliCommands      *[]string          `json:"cli_commands,omitempty"`
	DocsUrl          *string            `json:"docs_url,omitempty"`
	Homepage         *string            `json:"homepage,omitempty"`
	OfficialAccounts *map[string]string `json:"official_accounts,omitempty"`
	OrgOrOwner       *string            `json:"org_or_owner,omitempty"`
	PackageNames     *[]PackageRef      `json:"package_names,omitempty"`
	Repo             *string            `json:"repo,omitempty"`
	Slug             string             `json:"slug"`
	Tagline          *string            `json:"tagline,omitempty"`
}

// NameCollision Something else that shares this product's name. Observed, never recalled.
type NameCollision struct {
	Domain        *string `json:"domain,omitempty"`
	EvidenceUrl   string  `json:"evidence_url"`
	Name          string  `json:"name"`
	WhatItIs      string  `json:"what_it_is"`
	WhyConfusable *string `json:"why_confusable,omitempty"`
}

// PackageRef defines model for PackageRef.
type PackageRef struct {
	Name     string `json:"name"`
	Registry string `json:"registry"`
}

// Post One scraped discussion, normalized across platforms by scraping/mapper.py.
//
// This is the frozen contract T2 consumes. Field names match mapper.py's
// output exactly — it is the producer, this is the schema for what it makes.
type Post struct {
	Author                *string        `json:"author,omitempty"`
	Body                  *string        `json:"body,omitempty"`
	Channel               *string        `json:"channel,omitempty"`
	Comments              *[]PostComment `json:"comments,omitempty"`
	CreatedAt             *string        `json:"created_at,omitempty"`
	CreatedAtIsScrapeTime *bool          `json:"created_at_is_scrape_time,omitempty"`
	Id                    string         `json:"id"`
	Language              *string        `json:"language,omitempty"`
	NumComments           *int           `json:"num_comments,omitempty"`
	Relevance             *float32       `json:"relevance,omitempty"`
	Score                 *int           `json:"score,omitempty"`
	ScrapedAt             *string        `json:"scraped_at,omitempty"`
	SearchQuery           *string        `json:"search_query,omitempty"`
	Source                PostSource     `json:"source"`
	SourceId              *string        `json:"source_id,omitempty"`
	Title                 *string        `json:"title,omitempty"`
	Url                   string         `json:"url"`
}

// PostSource defines model for Post.Source.
type PostSource string

// PostComment defines model for PostComment.
type PostComment struct {
	Author *string `json:"author,omitempty"`
	Body   string  `json:"body"`
	Depth  *int    `json:"depth,omitempty"`
	IsOp   *bool   `json:"is_op,omitempty"`
	Score  *int    `json:"score,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// ProductDossier defines model for ProductDossier.
type ProductDossier struct {
	// Disambiguation Draft plus the score we compute ourselves rather than ask for.
	Disambiguation Disambiguation `json:"disambiguation"`
	Identity       Identity       `json:"identity"`
	Provenance     Provenance     `json:"provenance"`

	// Vocabulary How real users refer to the product when they talk about it.
	Vocabulary Vocabulary `json:"vocabulary"`
	What       What       `json:"what"`
}

// Provenance defines model for Provenance.
type Provenance struct {
	DegradedSources *[]string           `json:"degraded_sources,omitempty"`
	FieldConfidence *map[string]float32 `json:"field_confidence,omitempty"`
	GeneratedAt     time.Time           `json:"generated_at"`
	RuntimeMs       int                 `json:"runtime_ms"`
	Sources         *[]Source           `json:"sources,omitempty"`
}

// RedditTargets Where on Reddit this product is actually discussed.
//
// Subreddits alone miss most of it: in the reference scrape, 12 of 27 Reddit
// signals came from site-wide search, in subreddits nobody would have listed
// up front. So queries carry at least as much weight as subreddits.
type RedditTargets struct {
	SearchQueries *[]string `json:"search_queries,omitempty"`
	Subreddits    *[]string `json:"subreddits,omitempty"`
}

// ResultEvent Terminal event. Always last, always exactly one.
type ResultEvent struct {
	Event *string `json:"event,omitempty"`

	// Note Everything the run produced. Grows a field per stage as T3-T5 land.
	Note FieldNote `json:"note"`
}

// ScrapeTargets T1's output: what to scrape, derived from the dossier's discriminator.
type ScrapeTargets struct {
	Hackernews *HackerNewsTargets `json:"hackernews,omitempty"`

	// Rationale Why these targets, in one or two sentences. Shown to the operator so a bad expansion is visible before budget is spent.
	Rationale *string `json:"rationale,omitempty"`

	// Reddit Where on Reddit this product is actually discussed.
	//
	// Subreddits alone miss most of it: in the reference scrape, 12 of 27 Reddit
	// signals came from site-wide search, in subreddits nobody would have listed
	// up front. So queries carry at least as much weight as subreddits.
	Reddit *RedditTargets `json:"reddit,omitempty"`
}

// Source defines model for Source.
type Source struct {
	FetchedAt time.Time `json:"fetched_at"`
	Url       string    `json:"url"`
	Via       SourceVia `json:"via"`
}

// SourceVia defines model for Source.Via.
type SourceVia string

// StageEvent defines model for StageEvent.
type StageEvent struct {
	Detail *string          `json:"detail,omitempty"`
	Event  *string          `json:"event,omitempty"`
	Stage  StageEventStage  `json:"stage"`
	Status StageEventStatus `json:"status"`
}

// StageEventStage defines model for StageEvent.Stage.
type StageEventStage string

// StageEventStatus defines model for StageEvent.Status.
type StageEventStatus string

// Vocabulary How real users refer to the product when they talk about it.
type Vocabulary struct {
	AdjacentProducts   *[]string `json:"adjacent_products,omitempty"`
	CommonMisspellings *[]string `json:"common_misspellings,omitempty"`

	// FeatureJargon Product-specific words with no namesakes. Often a better search key than the product name itself.
	FeatureJargon *[]string `json:"feature_jargon,omitempty"`
	UserTerms     *[]string `json:"user_terms,omitempty"`
}

// What defines model for What.
type What struct {
	Category        *string   `json:"category,omitempty"`
	Description     *string   `json:"description,omitempty"`
	KeyFeatures     *[]string `json:"key_features,omitempty"`
	License         *string   `json:"license,omitempty"`
	Maturity        *string   `json:"maturity,omitempty"`
	PricingModel    *string   `json:"pricing_model,omitempty"`
	PrimaryUseCases *[]string `json:"primary_use_cases,omitempty"`
	Subcategory     *string   `json:"subcategory,omitempty"`
	TargetUsers     *[]string `json:"target_users,omitempty"`
	TechStack       *[]string `json:"tech_stack,omitempty"`
}
